# Generated by Django 2.2.3 on 2019-08-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='类别Id')),
                ('category_code', models.CharField(max_length=32, verbose_name='类别代码')),
                ('category_name', models.CharField(default='', max_length=256, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='城市Id')),
                ('city_code', models.CharField(max_length=32, verbose_name='城市代码')),
                ('city_name', models.CharField(default='', max_length=256, verbose_name='城市名称')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
    ]
