# Generated by Django 2.2.3 on 2019-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='类别代码'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='城市代码'),
        ),
    ]
