# Generated by Django 2.2.3 on 2019-08-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20190801_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='weight',
            field=models.FloatField(default=0, null=True, verbose_name='权重'),
        ),
    ]
