# Generated by Django 2.2.3 on 2019-08-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_city_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.FloatField(default=0, null=True, verbose_name='权重'),
        ),
    ]
