# Generated by Django 2.2.3 on 2019-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0003_auto_20190802_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], db_index=True, default=0, null=True, verbose_name='媒体状态'),
        ),
    ]
