# Generated by Django 2.2.3 on 2019-08-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0004_news_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='poster',
            field=models.URLField(default='', null=True, verbose_name='新闻头图'),
        ),
    ]
