# Generated by Django 2.2.3 on 2019-08-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Channel', '0005_news_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='weight',
            field=models.FloatField(default=0, null=True, verbose_name='权重'),
        ),
    ]
